# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {/media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/Proyecto_version_inicial_Diego/Iteracion 1/Iteracion 1.cache/wt} [current_project]
set_property parent.project_path {/media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/Proyecto_version_inicial_Diego/Iteracion 1/Iteracion 1.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Fifth_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Multiplier_P.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Ninth_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/OR_Module.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/FSM_Mult_Function.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/FPU_Multiplication_Function.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/RegisterMult.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Fourth_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Second_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/First_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Seventh_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/FF_T.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Eight_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Sixth_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Third_Phase_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Deco_Round_Mult.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/XOR_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Add_Subtract_M.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Zero_InfMult_Unit.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Zero_Decoder.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Universal_Shift_Register.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Shift_Module_Param.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/RegisterAdd.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Multiplexer_AC.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Invert_Sign.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Greater_Comparator.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Decoder_4_1.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Comparator_Less.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Comparator_Equal.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/add_sub_carry_out.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/add_subtract.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Zero_InfAdd_Unit.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Third_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Tenth_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Sixth_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Seventh_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Second_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/FSM_Add_Subtract.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Fourth_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/First_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Fifth_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Eight_N_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/Eight_NE_Phase.v
  /media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/RTL/FPU_Add_Subtract_Function.v
}
read_xdc {{/media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/Proyecto_version_inicial_Diego/Iteracion 1/Iteracion 1.srcs/constrs_1/new/time_constrains.xdc}}
set_property used_in_implementation false [get_files {{/media/francis/Acer/Users/Francis/Documents/GitHub/Proyecto_De_Graduacion/Proyecto_version_inicial_Diego/Iteracion 1/Iteracion 1.srcs/constrs_1/new/time_constrains.xdc}}]

synth_design -top FPU_Add_Subtract_Function -part xc7a100tcsg324-3
write_checkpoint -noxdef FPU_Add_Subtract_Function.dcp
catch { report_utilization -file FPU_Add_Subtract_Function_utilization_synth.rpt -pb FPU_Add_Subtract_Function_utilization_synth.pb }
